#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=12:0:0
#SBATCH --nodes=15
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=8
#SBATCH --constraint=cpu
#SBATCH -J GX_database
#SBATCH --mail-user=rogerio.jorge@wisc.edu
#SBATCH --mail-type=ALL

export OMP_PROC_BIND=spread
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

srun --cpu-bind=cores python /pscratch/sd/r/rjorge/CycleGAN/GX_database_create.py
